"""
3. WARRANTIES, LIABILITY AND GUARANTEES
IN NO EVENT SHALL CONTRACTOR BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, 
SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, 
ARISING OUT OF THE USE, MISUSE, OR UNLAWFUL USE OF THIS SOFTWARE AND ITS 
DOCUMENTATION, EVEN IF BIOCOM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH 
DAMAGE. THE LICENSEE, USER OR CLIENT OF THIS SOFTWARE IS EXCLUSIVELY CHARGED
WITH ENSURING THIS SOFTWARE IS NOT USED IN VIOLATION OF ANY CIVIL OR CRIMINAL
STATUTE OR PRIVATE POLICY.

EXCEPT AS INDICATED IN LEGALLY BINDING WRITINGS THAT SUPERSEDE THIS DISCLAIMER, 
BIOCOM SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT 
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
PARTICULAR PURPOSE. THE SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY, 
PROVIDED HEREUNDER IS PROVIDED "AS IS". BIOCOM HAS NO OBLIGATION TO 
PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

ANY PARTS OF THIS CLAUSE NOT SPECIFICALLY SUPERSEDED REMAIN VALID AND IN PLACE
REGARDLESS OF THE ESIXTENCE OF OTHER WARRRANTY DOCUMENTATION. 
"""
