""""

1. PUBLIC LICENSEE USE:
Any intellectual property issued to licensee under the PUBLIC_PICENSEE_USE.py 
License is allowed full of the intellectual property use as defined by the 
GNU Public License Version 2, June 1991 in accordance with the reservations
found in Clause2.RESERVATIONS_FOR_BIOCOM_SOFTWARE_AND_Author.py.   

[FOR REFERENCE ONLY, non-binding]
GNU Public License Version 2, June 1991

Copyright (C) 1989, 1991 Free Software Foundation, Inc.  
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""